project_folder: null
associations:
  api: gwas_catalog
  sig_p_value: 5e-8
  association_out_file: associations.csv
ld:
  api: ld_matrix
  ref_pop: CEU
  genome_build: grch37
  score: r
  mtag_in_file: mtag.txt
  snp_col: snp_name
  chr_col: chrom_name
  ld_out_file: ld_matrix.csv
