project_paths: 
  project_folder: null
  association_out_file: associations.csv
  ld_out_file: ld_matrix.csv
associations:
  api: gwas_catalog
  sig_p_value: 5e-8
ld:
  api: ld_matrix
  ref_pop: CEU
  genome_build: grch37
  score: r
  mtag_in_file: mtag.txt
  snp_col: null
  chr_col: null
