project_folder: C:\\Users\\Martin\\OneDrive\\Documents\\Study\\rp1\\JIA
associations:
  api: gwas_catalog
  sig_p_value: 5e-8
  association_out_file: associations.csv
ld:
  api: ld_matrix
  ref_pop: CEU
  genome_build: grch37
  score: r
  mtag_in_file: jia_mtag_craft.txt
  snp_col: rsid
  chr_col: chromosome
  ld_out_file: ld_matrix.csv
